
language: python
python: "3.6"
env:
  - BACKEND_SOURCE=$TRAVIS_BUILD_DIR/server DOCKER_SOURCE=$TRAVIS_BUILD_DIR/docker/release/Dockerfile -IMAGE_TAG=rakeshchoyal92/planimation-backend:latest
services:
  - docker
before_script: 
  - pip install docker-compose
jobs:
  include:
    - stage: "Build docker image"
      if: branch = develop
      script: 
        - cd $TRAVIS_BUILD_DIR/docker
        - docker build -t ${IMAGE_TAG} -f ${DOCKER_SOURCE} ${BACKEND_SOURCE}
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push ${IMAGE_TAG}
