language: python
python: "3.6"
env:
  - BACKEND_SOURCE=$TRAVIS_BUILD_DIR/server
services:
  - docker
before_install:
  - cd $TRAVIS_BUILD_DIR/docker
before_script: 
  - pip install docker-compose
# script:
  # - docker-compose run planimation_server sh -c "python manage.py test"
jobs:
  include:
    - stage: "test"
      name: "Test application"
      # script: docker-compose run planimation_server sh -c "python manage.py test"
      script: echo "Running Test!!"
    - stage: "deploy"
      if: branch = develop
      # script: docker-compose up
      script: echo "Deploy application"