
language: python
python: "3.6"
env:
  - BACKEND_SOURCE=$TRAVIS_BUILD_DIR/server
services:
  - docker
before_script: 
  - pip install docker-compose
jobs:
  include:
    if: type = pull_request
    - stage: "Test"
      name: "Test Application"
      script: echo "Test pass ..."
    - stage: "Build docker image"
      name: "Push Application to dockerhub"
      if: branch = develop
      name: "Push Application to dockerhub"
      script: 
        - echo "Push image to DockerHub"
        - cd $TRAVIS_BUILD_DIR/docker
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push rakeshchoyal92/planimation-backend:latest
